# Generated by fusen: do not edit by hand

test_that("input demo data is one row", {
  expect_true(inherits(plot_demographics, "function")) 
  expect_warning(plot_demographics(nyccensus::demos_data[["nCode"]]))
})
