# Generated by fusen: do not edit by hand

#' Plot demographics
#'
#' Generates a stacked bar plot of the proportion of different racial and ethnic groups for a given GEO_ID
#'
#' @param df data frame to generate demographic plot from (must contain only one row of data)
#'
#' @return a ggplot object
#'
#' @export
#' @examples
#' # save demographic data for woodside
#' woodside <- nyccensus::demos_data[["nCode"]] %>%
#'   dplyr::filter(GEO_ID == "Q64")
#' 
#' # generate plot
#' plot_demographics(woodside)
plot_demographics <- function(df) {
  if (nrow(df) > 1) {
    warning("Filter input demo data to single row for plotting")
  } else {
    # wrangle data
  plot_data <- df %>%
    dplyr::select(contains("Race_")) %>%
    tidyr::pivot_longer(
      cols = everything(),
      names_to = c("group", "race", "ethnicity"),
      names_sep = "_",
      values_to = "percentage"
    ) %>%
    dplyr::select(-group) %>%
    dplyr::mutate(race = dplyr::recode(race, "MoreThanOne" = "More than One",
                         "Amerind" = "Native American",
                         "Pacific" = "Pacific Islander"),
           ethnicity = dplyr::recode(ethnicity, "NotHispanic" = "Not Hispanic")) %>%
    # reverse factors
    dplyr::mutate(race = forcats::fct_rev(race),
           ethnicity = forcats::fct_rev(ethnicity))
  
  # save percent hispanic
  percent_hispanic <- plot_data %>%
    dplyr::group_by(ethnicity) %>%
    dplyr::summarize(total = sum(percentage)) %>%
    dplyr::filter(ethnicity == "Hispanic") %>%
    dplyr::mutate(total = round(total * 100, digits = 1)) %>%
    dplyr::pull(total)
  
  # calculate totals for bar labels
  race_totals <- plot_data %>%
    dplyr::group_by(race) %>%
    dplyr::summarize(percentage = sum(percentage)) %>%
    # to make which group to put label over
    dplyr::mutate(ethnicity = "Hispanic") %>%
    dplyr::arrange(percentage)
  
  # save factor levels
  race_levels <- race_totals$race
  
  # generate plot
  ggplot2::ggplot(plot_data, ggplot2::aes(fill=ethnicity, y=percentage, x=factor(race, levels = race_levels))) +
    ggplot2::geom_bar(position="stack", stat="identity") +
    ggplot2::geom_text(data = race_totals, ggplot2::aes(label = round(percentage * 100, digits = 1)),
              position=ggplot2::position_dodge(width=0.9),
              hjust = -.15, color = "grey20", size = 3) +
    ggplot2::scale_y_continuous(labels = scales::percent) +
    ggplot2::scale_fill_viridis_d(begin = 0.2, end = 0.6, direction = -1,
                         guide = ggplot2::guide_legend(reverse = TRUE)) +
    ggplot2::coord_flip(clip = "off") +
    ggplot2::labs(title = "Proportion of Population by Race and Ethnicity",
         subtitle = paste0("Across all race categories, ",
                           percent_hispanic,
                           "% of the population identifies as Hispanic/Latinx"),
         caption = "Data from the 2014-2018 American Community Survey (ACS) 5-year estimates") +
    theme_census() +
    ggplot2::theme(
      legend.position = "bottom",
      legend.title = ggplot2::element_blank(),
      axis.title.y = ggplot2::element_blank(),
      axis.title.x = ggplot2::element_blank()
    )
  }
}
