# Generated by fusen: do not edit by hand

#' Census Theme
#' 
#' Applies standard plotting theming to ggplot objects
#' 
#' @return a theme function
#' 
#' @export
#' @examples
#' ggplot2::ggplot(iris, ggplot2::aes(x = Sepal.Length)) +
#'   ggplot2::geom_histogram() +
#'   theme_census()
theme_census <- function(...){
  ggplot2::theme_minimal() +
    ggplot2::theme(
      # set default text family, size, and color
      text = ggplot2::element_text(
        family = "Open Sans",
        size = 10,
        color = "grey20"
      ),
      # left align y axis labels
      axis.text.y = ggplot2::element_text(
        hjust = 0
      ),
      # adjust size and face of axis titles
      axis.title = ggplot2::element_text(
        size = 10,
        face = "italic",
      ),
      # add spacing above x axis title
      axis.title.x = ggplot2::element_text(
        margin = ggplot2::margin(10, 0, 0, 0)
      ),
      # add spacing to right of y axis title
      axis.title.y = ggplot2::element_text(
        margin = ggplot2::margin(0, 10, 0, 0)
      ),
      # set size and face of plot title
      plot.title = ggplot2::element_text(
        size = 12
      ),
      # set size of plot subtitle
      plot.subtitle = ggplot2::element_text(
        size = 10,
      ),
      # set size and justification of caption
      plot.caption = ggplot2::element_text(
        size = 8,
        hjust = 0,
        margin = ggplot2::margin(10, 0, 0, 0)
      ),
      # add margin around plot
      plot.margin = ggplot2::margin(10, 10, 10, 10),
      # set size of strip text
      strip.text = ggplot2::element_text(
        family = "Open Sans",
        size = 8.5,
        color = "grey20"
      ),
      # align title, subtitle, and captions with y-axis labels
      plot.title.position = "plot",
      plot.caption.position = "plot",
      ...
    )
}
